services:
  user-management-db:
    image: postgres:15-alpine
    container_name: user-management-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: school-management-system-db
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network

volumes:
  pgdata:
    name: school-management-db-data
    driver: local

networks:
  app-network:
    driver: bridge